name: Epic
description: Crea una PR Epic per unire diverse PR
title: '[EPIC]: '
label: ['epic']
assignees: ['Smailen5']
body:
  - type: markdown
    attributes:
      value: |
        Descrivi cosa contiene l'epic.

  - type: textarea
    id: description
    attributes:
      label: 📋 Descrizione
      description: "Descrivi cosa include l'epic."
      placeholder: "Es. 'Epic per integrare le feature x e y'"
    validations:
      required: true

  - type: textarea
    id: closed_issues
    attributes:
      label: 📋 Issue Correlate
      description: "Inserisci solo la issue epic, le issue feature devono avere il loro numero di issue associato e stessa cosa vale per le sub-issue"
      placeholder: |
        - closes #(numero dell'epic)

  - type: textarea
    id: feature
    attributes:
      label: ✨ Cambiamenti principali
      description: "Elenca i cambiamenti in modo semplice e chiaro. Descrivendo cosa è stato aggiunto, migliorato, corretto in termini di funzionalità visibili all'utente."
      placeholder: |
        - Migliorato il componente x
        - Aggiunto il componente y

  - type: markdown
    attributes:
      value: |
        Per le modifiche tecniche controlla ogni PR correlata per maggiori dettagli.
