[build]
  command = "pnpm build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "18"

[functions]
  directory = "netlify/functions"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
