name: Epic 🚀
description: Crea un Epic
title: '[EPIC]: '
labels: ['epic']
projects: ['Portfolio']
assignees: 'Smailen5'
body:
  - type: markdown
    attributes:
      value: |
        Descrivi l'epic in modo chiaro e dettagliato.

  - type: textarea
    id: description
    attributes:
      label: 📋 Descrizione
      description: "Descrivi cosa include l'epic."
      placeholder: "Es. 'Epic per integrare le feature x e y'"
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: 💡 Motivazione
      description: 'Spiega perché crei questa epic e perché rilasciare queste feature insieme.'
      placeholder: "Es. 'Rilasciare insieme le feature x e y per una versione più corposa'"
    validations:
      required: true

  - type: textarea
    id: related_issues
    attributes:
      label: 📋 Issue Correlate
      description: "Inserisci le issue che vengono integrate in questa epic (usa una checklist)"
      value: |
        - [ ] #(numero dell'issue)
        - [ ] #(numero dell'issue)
    validations:
      required: true
